

ALTER TRIGGER [dbo].[SI_TR_GERA_MANIFESTO_COLETA]  
/* CRIADO POR NILZA EM 30/07/2021 - GERA MANIFESTO DE COLETA À PARTIR DA INCLUSÃO DE UM ROMANEIO */
ON [dbo].[RODRMC]

AFTER   UPDATE   
AS

BEGIN

DECLARE @CODFIL INT
DECLARE @CODRMC INT
DECLARE @CODMOT INT
DECLARE @CODVEI VARCHAR(10)
DECLARE @CODLIN VARCHAR(10)

SELECT	TOP 1
		@CODFIL = I.CODFIL,
		@CODRMC = I.CODRMC,
		@CODMOT = I.CODMOT,
		@CODVEI = I.CODVEI,
		@CODLIN = I.CODLIN
FROM INSERTED I 
				
WHERE I.TIPCAR = 1 AND
	 I.SITUAC = 'D' AND
	 NOT EXISTS ( SELECT TOP 1 T.CODRMC FROM TMP_GERA_REQUICAO_ABASTECIMENTO_COLETA T WITH(NOLOCK) WHERE T.CODFIL = I.CODFIL AND T.CODRMC =  I.CODRMC)


---- GRAVA O LOG DO QUE FOI GERADO AUTOMATICAMENTE --------------------------------------------------------
INSERT TMP_GERA_REQUICAO_ABASTECIMENTO_COLETA 
SELECT	TOP 1 
	    I.CODFIL,
		I.CODRMC,
		I.CODMOT,
		I.CODVEI,
		I.CODLIN
FROM INSERTED I 
				
WHERE I.TIPCAR = 1 AND
	 I.SITUAC = 'D'AND
	 NOT EXISTS ( SELECT TOP 1 T.CODRMC FROM TMP_GERA_REQUICAO_ABASTECIMENTO_COLETA T WITH(NOLOCK) WHERE T.CODFIL = I.CODFIL AND T.CODRMC =  I.CODRMC)


EXEC JOB_GERA_RMANIFESTO_COLETA @CODFIL,@CODRMC


END
GO


