

ALTER PROCEDURE [dbo].[JOB_GERA_RMANIFESTO_COLETA] (@CODFIL INT, @CODRMC INT) AS
/* CRIADO POR NILZA EM 03/08/2021 - SOLICITADO PELA DIRETORIA OPERACIOAL - CRIAR MANIFESTO DE COLETA APÓS UM ROMANEIO DE CARREGAMENTO SER EFETUADO */


DECLARE @CODMAN INT
DECLARE @ID_IMA INT
DECLARE @IDITE INT
DECLARE @ID_ITN INT
DECLARE @CODDOC INT
DECLARE @ORDIMA INT

--- ENCONTRA O PRÓXIMO NÚMERO VÁLIDO NA TABELA DE MANIFESTO - RODMAN ----------------------------------------------------
SET @CODMAN = (SELECT MAX(CODMAN) FROM RODMAN WHERE CODFIL = @CODFIL AND SERMAN = 'U') + 1

--- SETA A SEQUENCIA DOS MANIFESTOS NA TABELA RODIMA ---------------------------------------------------------------------
SET @ORDIMA = 0

---- INSERT NA TABELA RODMAN ---------------------------------------------------------------------------------------------
INSERT RODMAN (CODFIL, SERMAN, CODMAN, SITUAC, CODPAD, CODMO1, AUTFOR, TIPMAN, DATEMI, PLACA, PLACA2, ESTDES, DATSAI, CODLIN, LINTRE,  FILDES, DATINI, DATLME, NUMVIA, KMTINI, KMTFIN, CUSPED,  PEDTER, CODHOR,SEQFIS,  ATUMOT, ATUVEI, DOCFIS,DATINC, USUINC,DATATU, USUATU, CUSMAX, TIPRED, LIBERA , SITGER, CONSEM, ATURED, VIAGEM, SITCON, MDFEAUT, MDFEENC, TRAVEI, UNITOM , NMCIOT, OBSERV, IMAPAG, IMAREM, IMADES, FORTER, CODCLIFOR, NUMAWB)
SELECT		R.CODFIL, 'U', @CODMAN, 'D', 1, R.CODMOT, (SELECT MAX(AUTFOR) FROM RODMAN) + 1, '7', R.DATREF, R.CODVEI, R.PLACA2, 
			M.ESTADO, R.DATREF, R.CODLIN, R.CODLIN, M.FILRES, DATEADD(HOUR, 12, R.DATREF), DATEADD(HOUR, 12, R.DATREF), 0, 0,0,0,0, (SELECT TOP 1 RODHOR.CODHOR FROM RODHOR WHERE RODHOR.SITUAC = 'A' AND RODHOR.CODLIN = R.CODLIN), (SELECT MAX(SEQFIS) FROM RODMAN WHERE CODFIL = @CODFIL AND SERMAN = 'U') + 1, 'S', 'S', 'N', GETDATE(), 'IMPORTACAO', GETDATE(), 'IMPORTACAO', 0 , 'N', 'N', 'P', 'N', 'N',0 ,'A', 'N', 'N', 'N', 'N', 0 
			, 'GERADO AUTOMATICAMENTO PELO ROMANEIO ' + CONVERT(VARCHAR(2), R.CODFIL) +'-'+CONVERT(VARCHAR(10),R.CODRMC)
			,(SELECT TOP 1 RODOCS.CODPAG FROM RODOCS INNER JOIN RODIRC ON RODOCS.FILOCS = RODIRC.FILDOC AND RODOCS.CODOCS = RODIRC.CODDOC AND RODOCS.SEROCS = RODIRC.SERDOC WHERE R.CODRMC = RODIRC.CODRMC AND R.CODFIL = RODIRC.FILRMC ORDER BY RODIRC.CODDOC  ASC ) AS PAGADOR
			,(SELECT TOP 1 RODOCS.CODREM FROM RODOCS INNER JOIN RODIRC ON RODOCS.FILOCS = RODIRC.FILDOC AND RODOCS.CODOCS = RODIRC.CODDOC AND RODOCS.SEROCS = RODIRC.SERDOC WHERE R.CODRMC = RODIRC.CODRMC AND R.CODFIL = RODIRC.FILRMC ORDER BY RODIRC.CODDOC  ASC ) AS REMETENTE
			,(SELECT TOP 1 RODIOC.CODDES FROM RODIOC INNER JOIN RODIRC ON RODIOC.FILOCS = RODIRC.FILDOC AND RODIOC.CODOCS = RODIRC.CODDOC AND RODIOC.SEROCS = RODIRC.SERDOC WHERE R.CODRMC = RODIRC.CODRMC AND R.CODFIL = RODIRC.FILRMC ORDER BY RODIRC.CODDOC  ASC ) AS DESTINATARIO
			,R.FORTER, R.FORTER, @CODRMC
FROM RODRMC R WITH(NOLOCK) LEFT OUTER JOIN RODLIN L WITH(NOLOCK) ON R.CODLIN = L.CODLIN		
			  LEFT OUTER JOIN RODMUN M  WITH(NOLOCK) ON L.PONFIM = M.CODITN
			  LEFT OUTER JOIN RODFIL F  WITH(NOLOCK) ON M.FILRES = F.CODFIL
			  LEFT OUTER JOIN RODFIL FL WITH(NOLOCK) ON R.CODFIL = FL.CODFIL
			  LEFT OUTER JOIN RODMUN ML WITH(NOLOCK) ON FL.CODMUN = ML.CODMUN
			 

WHERE R.CODFIL = @CODFIL AND
	  R.CODRMC = @CODRMC


DECLARE CURITEM CURSOR FOR SELECT DISTINCT CODDOC
						FROM RODIRC R
								WHERE R.FILRMC = @CODFIL AND
									  R.CODRMC = @CODRMC

								

OPEN CURITEM
	FETCH NEXT FROM CURITEM INTO  @CODDOC
		WHILE (@@FETCH_STATUS<>-1) 
		BEGIN

-------- INCREMENTO-----------------------------------------------------------------------------------
SET @ID_IMA = (SELECT MAX(ID_IMA) FROM RODIMA ) + 1
SET @ORDIMA = @ORDIMA + 1



------- INSERT NA RODIMA - ITENS DO MANIFESTO ------------------------------------------------------
		INSERT RODIMA (ID_IMA ,  CODMAN ,  FILMAN ,  TIPDOC ,  FILDOC ,  SERDOC ,  CODDOC ,  DATINC ,  DATATU ,  USUATU ,  CUSMAN ,  LIBREP ,  DATREP ,  USUREP ,  ORDEM ,  MANORI ,  FILORI ,  ORDMAN ,  CUSNOT ,  PESOKG ,  CODPAG ,  SERORI ,  SERMAN ,  CARRET ,  OBSERV ,  BPGTER ,  CROSSD ,  FILCRO ,  DISTAN ,  LATORI ,  LONORI ,  LATDES ,  LONDES)
		SELECT DISTINCT	@ID_IMA, @CODMAN, @CODFIL, 'S', R.FILDOC,R.SERDOC, R.CODDOC, GETDATE(), GETDATE(), 'IMPORTACAO', 0, NULL, NULL, NULL, @ORDIMA,  NULL, NULL, @ORDIMA, SUM(R.VLRMER), SUM(R.PESOKG), R.CODCLIFOR, NULL, 'U', NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
		FROM RODIRC R WITH(NOLOCK)
		WHERE R.FILRMC = @CODFIL AND
			  R.CODRMC = @CODRMC AND
			  R.CODDOC = @CODDOC
		GROUP BY R.FILDOC,R.SERDOC, R.CODDOC, R.CODCLIFOR

------- FIM DO CURSOR ----------------------------------------------------------------------------------

FETCH NEXT FROM CURITEM INTO  @CODDOC
	END
	DEALLOCATE CURITEM
	---- CHAMA PROCEDURE DE NOTAS IMPORTAÇÃO DE NOTAS DO ROMANEIO --------------------------------------------------
	EXEC JOB_GERA_RMANIFESTO_COLETA_NOTA @CODFIL, @CODRMC,  @CODMAN, @CODFIL
GO


