
CREATE PROCEDURE [dbo].[JOB_GERA_RMANIFESTO_COLETA_NOTA] @CODFIL INT, @CODRMC INT , @CODMAN INT, @FILMAN INT AS
/* CRIADO POR NILZA EM 03/08/2021 - SOLICITADO POR DIRETORIA OPERACIONAL - UTILIZADO PELA PROCEDURE JOB_GERA_RMANIFESTO_COLETA - NOTAS DO ROMANEIO DE CARREGAMENTO  */

DECLARE @ID_IMA INT
--DECLARE @CODFIL INT
DECLARE @IDITE INT
DECLARE @ID_ITN INT
DECLARE @CODDOC INT
DECLARE @ORDIMA INT

------ INICIO DO CURSOR  - LOCALIZA AS NOTAS VINCULADAS AO ROMANEIO DE CARREGAMENTO -----------------------------------------------
DECLARE CURITEM2 CURSOR FOR SELECT ID_ITN
						FROM RODIRC R
								WHERE R.FILRMC = @CODFIL AND
									  R.CODRMC = @CODRMC

									

OPEN CURITEM2
	FETCH NEXT FROM CURITEM2 INTO  @ID_ITN
		WHILE (@@FETCH_STATUS<>-1) 
		BEGIN


--- ENCONTRA O PRÓXIMO NÚMERO VÁLIDO NA TABELA DE NOTAS DO MANIFESTO - RODIMR ----------------------------------------------------
SET @IDITE = (SELECT MAX(ID_ITE) FROM RODIMR )+1

		INSERT RODIMR (CODMAN, FILMAN,  TIPDOC, FILDOC, SERDOC ,  CODDOC,   ID_ITE,   CODCLIFOR, NOTFIS,   SERIEN,   CODRMC, FILRMC,    USUATU, DATATU, SERMAN) 
		SELECT	DISTINCT	  @CODMAN, @FILMAN, 'S',   R.FILDOC, R.SERDOC, R.CODDOC, @IDITE, R.CODCLIFOR, R.NOTFIS, R.SERIEN, R.CODRMC, R.FILRMC,  'IMPORTACAO', GETDATE(), 'U'
		FROM RODIRC R WITH(NOLOCK)
		WHERE R.FILRMC = @CODFIL AND
				R.CODRMC = @CODRMC AND
				R.ID_ITN = @ID_ITN 


------ FIM DO CURSOR
FETCH NEXT FROM CURITEM2 INTO  @ID_ITN
	END
	--END
	DEALLOCATE CURITEM2
GO


